# Databricks notebook source
import yaml
from pyspark.sql.functions import round, sum, year

spark.conf.set("spark.sql.shuffle.partitions", "auto")

with open("../config/config.yaml", "r") as f:
    cfg = yaml.safe_load(f)

silver = cfg["tables"]["silver"]
gold   = cfg["tables"]["gold"]

# COMMAND ----------

silver_sales = spark.table(silver["sales"])

# COMMAND ----------

# Total profit generated by a customer for a particular product sub-category in a specific year
gold_profit_agg = silver_sales \
    .withColumn("order_year", year("order_date")) \
    .groupBy(
        "order_year",
        "product_category",
        "product_sub_category",
        "customer_id",
        "customer_name"
    ) \
    .agg(
        round(sum("profit"), 2).alias("total_profit")
    ).sort(
        "order_year")

display(gold_profit_agg)

# COMMAND ----------

if gold_profit_agg.count() == 0:
    raise Exception(f"gold_profit_agg is empty,aborting write to {gold['profit_aggregation']}")

gold_profit_agg.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .partitionBy("order_year") \
    .saveAsTable(gold["profit_aggregation"])

print(f"{gold['profit_aggregation']}: {gold_profit_agg.count()} rows")

# COMMAND ----------

display(spark.table(gold["profit_aggregation"]))